bme/events/routes.py
from asyncio import events
from bme import db
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from bme.events.form import PostEventForm
from bme.model import  Event
from flask_login import current_user, login_required
from bme.events.utils import notifyOnBookingCancellation, notifyOnEventCancellation, notifyOnEventEdit
from bme.users.utils import saveProfilePicture, checkAttending, sendBookingConfirmationEmail




events = Blueprint('events', __name__)

#app.route becomes blueprint.route

#Route to allow users to create a new event
@events.route("/event/new", methods=['GET', 'POST'])
@login_required
def newEvent():
    form = PostEventForm()

    if form.validate_on_submit():
        
        event= Event( title=form.title.data, 
                    content = form.description.data, 
                    author=current_user,
                    date = form.date.data)
    
        if form.image.data:
            eventImageFile = saveProfilePicture(form.image.data, 2)
            event.image = eventImageFile
            db.session.commit()

        db.session.add(event)
        db.session.commit()
        flash("Event has been posted", "success")
        return redirect(url_for('main.home'))

    return render_template('create_event.html', title="New Event", heading="Post an Event",form =form)



#Route to allow users to view event details where they can attend/cancel booking
#users can also see the list of attendees provided they created that event
#<post_id> represents the variable of the post to view i.e.datatype = int
@events.route("/event/<int:event_id>")
@login_required
def viewEvent(event_id):

    event = Event.query.get_or_404(event_id) 

    return render_template('view_event.html', attending = checkAttending(event), title = event.title, event=event)



#Route for when users opt to attend an event
#<post_id> represents the variable of the post to view i.e.datatype = int
@events.route("/event/<int:event_id>", methods=['GET', 'POST'])
@login_required
def attendEvent(event_id):

    event = Event.query.get_or_404(event_id) 
    event.atendees.append(current_user)

    db.session.commit()
    sendBookingConfirmationEmail(event)
    flash('Thanks for attending, kindly check your email for confirmation', 'success')
    return redirect(url_for('main.home'))


#Route for when user cancels their booking for an event
#<post_id> represents the variable of the post to view i.e.datatype = int
@events.route("/event/<int:event_id>/cancel", methods=['POST'])
@login_required
def removeAttendee(event_id):

    event = Event.query.get_or_404(event_id) 
    current_user.attending.remove(event)
    db.session.commit()

    notifyOnBookingCancellation(event)

    flash('Booking cancelled, kindly check your email for cancellation confirmation', 'success')
    return redirect(url_for('main.home'))




#Route for when a user who created an event, now wants to edit it
#<post_id> represents the variable of the post to view i.e.datatype = int
@events.route("/event/<int:event_id>/update", methods=['GET', 'POST'])
@login_required
def editEvent(event_id):

    event = Event.query.get_or_404(event_id) 

    if event.author != current_user:
        abort(403) 
    
    form = PostEventForm()
    #all the attendees will be notified of the updated details for the event
    if form.validate_on_submit():
        event.title = form.title.data   
        event.content = form.description.data
        if form.image.data:
            eventImageFile = saveProfilePicture(form.image.data, 2)
            event.image = eventImageFile
        db.session.commit() 
        notifyOnEventEdit(event)
        flash('Your event has been updated!', 'success')
        return redirect(url_for('events.viewEvent', event_id = event.id))

    elif request.method == "GET":
        form.title.data = event.title
        form.description.data = event.content
            
    return render_template('create_event.html', title="Update Event", heading ="Edit Event", form =form)


#Route for when a user who created an event, now wants to delete it
#<post_id> represents the variable of the post to view i.e.datatype = int
@events.route("/event/<int:event_id>/delete", methods=['POST'])
@login_required
def deleteEvent(event_id):

    event = Event.query.get_or_404(event_id) 

#all the attendees will be notified of the event cancellation
    if event.author != current_user:
        abort(403) 
    notifyOnEventCancellation(event)

    db.session.delete(event)
    db.session.commit()

    flash('Your event has been deleted', 'success')
    return redirect(url_for('main.home'))

bme/main/routes.py
from flask import render_template, request
from bme.model import Event
from flask_login import login_required




from flask import Blueprint

main = Blueprint('main', __name__)

#app.route becomes blueprint.route

#This rperesents the home route, showing the home page
#multiple decorators for the same page
@main.route("/")
@main.route("/home")
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    events = Event.query.order_by(Event.id.desc()).paginate(per_page=5, page=page)
    return render_template("home.html", events = events, showSidePanel=True)

bme/users/routes.py
from bme import db, bcrypt
from flask import render_template, url_for, flash, redirect, request
from bme.users.form import RegistrationForm, LoginForm, UpdateAccountForm, RequestPasswordResetForm, ResetPasswordForm
from bme.model import User, Event
from flask_login import login_user, current_user, logout_user, login_required
from bme.users.utils import saveProfilePicture, sendResetPasswordEmail, sendWelcomeEmail

from flask import Blueprint


users = Blueprint('users', __name__)

#only contains route specific to the users blueprint

#app.route becomes blueprint.route
#this route accepts both GET and POST requests now
@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    regForm = RegistrationForm()
    #validating the form before returning/posting it
    if regForm.validate_on_submit():
        hashedPassword = bcrypt.generate_password_hash(regForm.password.data).decode('utf-8')           #hash to string hence the utf-8
        user = User(firstName = regForm.firstName.data, 
                    surName = regForm.surName.data, 
                    studentNumber = regForm.studentNumber.data, 
                    email = regForm.email.data,
                    password = hashedPassword)
        #adds the user to the db
        db.session.add(user)
        db.session.commit()
        flash(f'Welcome {regForm.firstName.data}!', 'success')
        login_user(user)
    
        sendWelcomeEmail(user)        
    
        return redirect(url_for('main.home'))            #home is the name of the function

    return render_template("register.html", title = "Register", form=regForm)




#For user login
@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    loginForm = LoginForm()
    #validating the form before returning/posting it
    if loginForm.validate_on_submit():
        user = User.query.filter_by(email = loginForm.email.data).first()
        if user and bcrypt.check_password_hash(user.password, loginForm.password.data):
            login_user(user, remember= loginForm.remember.data)
            nextPage = request.args.get("next")

            if nextPage:
                return redirect(nextPage)
            flash(f'Welcome back {user.firstName}!', 'success')
            return redirect(url_for('main.home'))             #home is the name of the function
        else:
            flash(f'Unsuccessful login - Please try again', 'danger')  
    return render_template("login.html", title = "Login", form=loginForm)





#For user logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))



#Allows the user to view their account, also allowing them to update their account
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    updateAForm= UpdateAccountForm()

    if updateAForm.validate_on_submit():

        if updateAForm.profilePicture.data:

            profilePictureFile = saveProfilePicture(updateAForm.profilePicture.data, 1)
            current_user.profilePicture = profilePictureFile
            db.session.commit()
            flash("Account has been updated!", "success")
            return redirect(url_for('users.account'))
            

    page = request.args.get('page', 1, type=int)
    eventsPosted = Event.query.filter_by(userId = current_user.id).order_by(Event.date.desc()).paginate(page=page, per_page=5)

    profilePic = url_for('static', filename='profilePics/' + current_user.profilePicture)
    return render_template('account.html', title="Account", user= current_user, profilePicture = profilePic, form=updateAForm, eventsPosted = eventsPosted)



#To view another user, by clikcing on their name from their post on the home screen
@users.route("/user/<int:user_id>")
@login_required
def viewUser(user_id):
    page = request.args.get('page', 1, type=int)

    user = User.query.get_or_404(user_id) 
    fullName = "- " +user.firstName + " " +user.surName
    eventsPosted = Event.query.filter_by(userId = user_id).order_by(Event.date.desc()).paginate(page=page, per_page=5)

    return render_template('view_user.html', title=fullName, user=user, eventsPosted=eventsPosted)



#When user's click the forgot password? button on the login page.
#User enters their email where reset instructions will be sent
@users.route("/reset", methods=['GET', 'POST'])
def requestPasswordReset():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestPasswordResetForm()

    #get the user who wants to reset their password, using the email provided on their request form
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        sendResetPasswordEmail(user)
        flash('Please check your email to reset your password - this should be done within 10 minutes', 'info')
        return redirect(url_for('users.login'))


    return render_template('reset_request.html', title="Reset Password", form=form)


#to reset the password - must be done within 10 minutes for requesting the reset
@users.route("/reset/<token>", methods=['GET', 'POST'])
def resetPassword(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)       #returns the User associated with the token, provided the token hasnt expired

    #if not done within 10 mins
    if user is None:
        flash('Invalid/Expired token. Kindly retry again!', 'warning')
        return redirect(url_for('users.requestPasswordReset'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashedPassword = bcrypt.generate_password_hash(form.password.data).decode('utf-8')           #hash to string hence the utf-8
        user.password = hashedPassword        
        db.session.commit()
        flash(f'Password has been reset!', 'success')
        return redirect(url_for('users.login'))            #home is the name of the function

    return render_template('reset_password.html', title="Reset Password", form=form)


#Allows users to see which events they are attending
@users.route("/attending", methods=['GET', 'POST'])
@login_required
def viewAttendingEvents():

    return render_template('view_attending.html', title="Attending")

bme/templates/account.html
{% extends "layout.html" %}

{% block content %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{profilePicture}}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.firstName }}&nbsp;{{ current_user.surName }}</h2>
            <p class="text-secondary">Student #:&nbsp;{{ current_user.studentNumber }}</p>
            <p class="text-secondary">Email:&nbsp;{{ current_user.email }}</p>
        </div>
    </div>

    <form method="POST" action="" enctype="multipart/form-data">

        {{ form.hidden_tag() }}

        <fieldset class="form-group">

            <legend class="border-bottom mb-4">Account Details</legend>

            <div class="form-group">
                {{ form.profilePicture.label() }}
                {{ form.profilePicture(class="form-control-file") }}

                {% if form.profilePicture.errors %}
                    {% for error in form.profilePicture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}

            </div>

        </fieldset>

        <div class="form-group">
            {{ form.submit(class= "btn btn-outline-info") }}
        </div>

    </form>

    <legend class="border-bottom mb-4">Event History - {{eventsPosted.total}}</legend>

    {% for event in eventsPosted.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img"
            src="{{ url_for('static', filename = 'profilePics/' + event.author.profilePicture) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="#">{{ event.author.firstName }}&nbsp;{{ event.author.surName }} </a>
                <p class="float-right font-weight-bold">On {{ event.date.strftime('%d-%b-%Y') }}</p>
            </div>
            <h2><a class="article-title" style="color:#000cee;" href="{{ url_for('events.viewEvent', event_id=event.id) }}">{{
                event.title }}</a></h2>
            <p class="article-content">{{ event.content }}</p>
            {% if event.image %}
            <div class="div" style="text-align:center;">
                <img style="width:100%; height: 100%;" src="{{ url_for('static', filename = 'eventPics/' + event.image) }}">
            </div>
            {% endif %}
        </div>
    </article>
    {% endfor %}
    
    {% for page_num in eventsPosted.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
        {% if page_num %}
    
            {% if eventsPosted.page==page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.viewUser', user_id =user.id, page=page_num) }}">{{page_num}}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.viewUser', user_id =user.id, page=page_num)}}">{{page_num}}</a>
            {% endif %}
    
        {% else %}
        ...
        {% endif %}
    {% endfor %}
    
</div>


{% endblock content %}

bme/templates/confirmation_email.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <style>
        h1 {text-align: center;
        font-weight: bold;}
        h2   {text-align: left;}
    
        </style>
</head>
<body>
    
   <h1>Hey {{name}}, thanks for confirming</h1>
   <h2>Event: {{eventName}}</h2>
   <h2>Organizer: {{organizerFirstName}} {{organizerSurName}}</h2>
   <h2>Event Date: {{ date.strftime('%d-%b-%Y') }}</h2>



   
</body>
</html>

bme/templates/event_cancellation.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <style>
        h1 {text-align: center;
        font-weight: bold;}
        h2   {text-align: left;}
    
        </style>
</head>
<body>
    
   <h1>Dear {{firstName}}, the following event has been cancelled</h1>
   <h2>Event: {{eventName}}</h2>
   <h2>Event Date: {{ date.strftime('%d-%b-%Y') }}</h2>
   <h2>We sincerely apologise for any inconviniences</h2>

   
</body>
</html>

bme/templates/home.html
<!--Like inheritance,we'll use everything from the parent html file i.e. layout.html-->
<!-- reduces code duplication-->
{% extends "layout.html" %}

<!--block name is content-->
{% block content %}

    {% for event in events.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src = "{{ url_for('static', filename = 'profilePics/' + event.author.profilePicture) }}" >
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.viewUser', user_id  =event.author.id) }}">{{ event.author.firstName }}&nbsp;{{ event.author.surName }} </a>
            <p class="float-right font-weight-bold">On {{ event.date.strftime('%d-%b-%Y') }}</p>
          </div>
          <h2><a class="article-title" style="color:#000cee;" href="{{ url_for('events.viewEvent', event_id=event.id) }}">{{ event.title }}</a></h2>
          <p class="article-content">{{ event.content }}</p>
          {% if event.image %}
          <div class="div" style="text-align:center;">
            <img style ="width:100%; height: 100%;" src = "{{ url_for('static', filename = 'eventPics/' + event.image) }}" >
          </div>
          {% endif %}

      


        </div>
      </article>
    {% endfor %}

    {% for page_num in events.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}

        {% if events.page==page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{page_num}}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{page_num}}</a>
        {% endif %}  

      {% else %}
      ...
      {% endif %}
    {% endfor %}





{% endblock content %}

bme/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename = 'main.css') }}">
  <title>Book My Event {{title}}</title>
</head>


<body>
  <header class="site-header">

    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">

        <a class="navbar-brand mr-4" href="/">Book My Event</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}

          </div>
        </div>
      </div>
    </nav>
  </header>


  <!--Block is the part which the child section will override-->
  <!--Name of the block must be content in the child files inorder to override this block-->


  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        <!--Get all the mesages with category=success-->
        {% with messages = get_flashed_messages(with_categories = true) %}
        <!--If there are any messages-->
        {% if messages %}
        <!--For every category and message in messages-->
        {% for category, message in messages %}
        <div class="alert alert-{{category}}">
          {{message}}
        </div>
        {% endfor %}

        {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
      </div>
      {% if showSidePanel %}
      <div class="col-md-4">
        <div class="content-section">
          <h3>Quick Links</h3>
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">
              <a  href="{{ url_for('events.newEvent') }}">Post an Event</a>
            </li>
            <li class="list-group-item list-group-item-light">
              <a href="{{ url_for('users.viewAttendingEvents') }}">Events you are attending</a>
            </li>
          </ul>
          </p>
        </div>
      </div>
      {% endif %}
    </div>
  </main>




  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

bme/templates/login.html
{% extends "layout.html" %}

{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            
            {{ form.hidden_tag() }}
            
            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Log In</legend>


                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    <!--If theres an error in the email, display the eror-->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}               
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    <!--If theres an error in the password, display the eror-->
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}                  
                </div>

                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>

            </fieldset>

            <div class="form-group">
                {{ form.submit(class= "btn btn-outline-info") }}
            </div>

            <small class="text-muted ml-2">
                <a href="{{ url_for('users.requestPasswordReset') }}">Forgot Password?</a>
            </small>

        </form>
    </div>  

    <div class="border-top">  
        <small class="text-muted">
            <!-- #login is thee name of function, not the route name-->
            Don't have an Account? <a class="ml-2" href= "{{ url_for('users.register') }}">Register today!</a>
        </small>
    </div>
      




{% endblock content %}

bme/templates/view_attending.html
<!--Like inheritance,we'll use everything from the parent html file i.e. layout.html-->
<!-- reduces code duplication-->
{% extends "layout.html" %}

<!--block name is content-->
{% block content %}



<div class="media">
    <img class="rounded-circle account-img"
        src="{{ url_for('static', filename = 'profilePics/' + current_user.profilePicture) }}">
    <div class="media-body">
        <h2 class="account-heading">{{ current_user.firstName }}&nbsp;{{ current_user.surName }}</h2>
        <p class="text-secondary">Student #:&nbsp;{{ current_user.studentNumber }}</p>
        <p class="text-secondary">Email:&nbsp;{{ current_user.email }}</p>
    </div>
</div>


<legend class="border-bottom mb-4">Events you are attending</legend>


{% for event in current_user.attending %}
<article class="media content-section">
    <div class="media-body">

        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.viewUser', user_id = event.author.id) }}">{{ event.author.firstName }}&nbsp;{{ event.author.surName }} </a>
            <p class="float-right font-weight-bold">On {{ event.date.strftime('%d-%b-%Y') }}</p>        
        </div>
        <h2><a class="article-title" style="color:#000cee;" href="{{ url_for('events.viewEvent', event_id=event.id) }}">{{ event.title }}</a></h2>
        
        <p class="article-content">{{ event.content }}</p>
        {% if event.image %}
        <div class="div" style="text-align:center;">
            <img style="width:100%; height: 100%;" src="{{ url_for('static', filename = 'eventPics/' + event.image) }}">
        </div>
        {% endif %}
    </div>
</article>
{% endfor %}







{% endblock content %}

bme/templates/view_event.html
<!--Like inheritance,we'll use everything from the parent html file i.e. layout.html-->
<!-- reduces code duplication-->
{% extends "layout.html" %}

<!--block name is content-->
{% block content %}


<article class="media content-section">
  <img class="rounded-circle article-img"
    src="{{ url_for('static', filename = 'profilePics/' + event.author.profilePicture) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{ url_for('users.viewUser', user_id=event.author.id) }}">{{ event.author.firstName }}&nbsp;{{ event.author.surName }} </a>
      <p class="float-right font-weight-bold">On {{ event.date.strftime('%d-%B-%y') }}</p>

      {% if event.author == current_user %}
      <div>
        <a href="{{ url_for('events.editEvent', event_id=event.id) }}" class="btn btn-secondary btn-sm mt-1 mb-1">Edit</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
          data-target="#deleteModal">Delete</button>
      </div>

      {% elif attending %}
      <div>
        <button type="button" class="btn btn-info btn-sm m-1" disabled >Attending</button>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
          data-target="#cancelModal">Cancel booking</button>
      </div>

      {% else %}
      <div>
        <button type="button" class="btn btn-info btn-sm m-1" data-toggle="modal"
          data-target="#attendModal">Attend</button>
      </div>

      {% endif %}

    </div>

    <h2 class="article-title text-center">{{ event.title }}</h2>
    <p class="article-content">{{ event.content }}</p>
    
    {% if event.image %}
    <div class="div" style="text-align:center;">
      <img style="width:100%; height: 100%;" src="{{ url_for('static', filename = 'eventPics/' + event.image) }}">
    </div>
    {% endif %}

    {% if event.author == current_user %}
    <legend class="border-bottom mb-4">Atendees</legend>


      {% for attendee in event.atendees %}
        <article class="media content-section">
          <div class="media-body">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename = 'profilePics/' + attendee.profilePicture) }}">
            
            <a class="mr-2" href="{{ url_for('users.viewUser', user_id  =attendee.id) }}">{{ attendee.firstName }}&nbsp;{{ attendee.surName }} </a>
            <small class="text-muted float-right">{{ attendee.studentNumber }}</small>
           
            
          </div>
        </article>
      {% endfor %}

    {% endif %}

  </div>

</article>

<!-- Delete event Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Event?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this event?</p>
        <p style="color:red;">This cannot be undone</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>

        <form action="{{ url_for('events.deleteEvent', event_id= event.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Yes">
        </form>

      </div>
    </div>
  </div>
</div>

<!-- Attendance confirmation Modal -->
<div class="modal fade" id="attendModal" tabindex="-1" role="dialog" aria-labelledby="attendModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="attendModalLabel">Attend Event?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to attend this event?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>

        <form action="{{ url_for('events.attendEvent', event_id= event.id) }}" method="POST">
          <input class="btn btn-success" type="submit" value="Yes">
        </form>

      </div>
    </div>
  </div>
</div>


<!-- Cancel booking Modal -->
<div class="modal fade" id="cancelModal" tabindex="-1" role="dialog" aria-labelledby="cancelModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="cancelModalLabel">Cancel Booking?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to cancel your booking?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>

        <form action="{{ url_for('events.removeAttendee', event_id= event.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Yes">
        </form>

      </div>
    </div>
  </div>
</div>


{% endblock content %}